export interface SmsSample {
    id: number;
    body: string;
    sender: string;
    expected: {
        isTransaction: boolean;
        type: 'expense' | 'income' | null;
        amount: number | null;
        merchantSubstring?: string;
    };
    category: 'debit' | 'credit' | 'otp' | 'promo';
}

export const SMS_SAMPLES: SmsSample[] = [
    // ═════════════════════════════════════════════
    // DEBIT SAMPLES (1–120)
    // ═════════════════════════════════════════════
    { id: 1, body: 'Rs.450.00 debited from A/c XX1234 at Amazon on 03-Mar-2026', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 450, merchantSubstring: 'Amazon' }, category: 'debit' },
    { id: 2, body: 'Your A/c XX5678 is debited by Rs.1,250.50 on 02-03-2026 at Swiggy.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 1250.50, merchantSubstring: 'Swiggy' }, category: 'debit' },
    { id: 3, body: 'Rs 899 spent on your card ending 4321 at Flipkart on 01/03/2026.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 899 }, category: 'debit' },
    { id: 4, body: 'Payment of Rs.2,500 made to Zomato from A/c XX9876 on 28-Feb-2026', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 2500, merchantSubstring: 'Zomato' }, category: 'debit' },
    { id: 5, body: 'INR 3,450.00 has been debited from your account XX4567 for purchase at Myntra.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 3450 }, category: 'debit' },
    { id: 6, body: 'Rs.150 paid to BigBasket via UPI from A/c XX1111 on 03/03/2026', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 150, merchantSubstring: 'BigBasket' }, category: 'debit' },
    { id: 7, body: 'Rs.75.00 sent to merchant@upi via UPI. A/c XX2222 debited.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 75 }, category: 'debit' },
    { id: 8, body: 'Your card XX3456 has been charged Rs.5,999.00 at Apple Store on 01-03-2026.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 5999 }, category: 'debit' },
    { id: 9, body: 'Withdrawal of Rs.10,000 from ATM. A/c XX6789 debited on 28-02-2026.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 10000 }, category: 'debit' },
    { id: 10, body: 'Rs.2,199.00 deducted from your A/c XX4444 for Uber ride on 03-Mar-2026', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 2199, merchantSubstring: 'Uber' }, category: 'debit' },
    { id: 11, body: 'Txn of Rs.325 at PVR Cinemas on 02/03/2026. Card XX5555.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 325, merchantSubstring: 'PVR' }, category: 'debit' },
    { id: 12, body: 'Rs 1,800 debited from A/c XX7890 to Ola Cabs on 01-03-26.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 1800, merchantSubstring: 'Ola' }, category: 'debit' },
    { id: 13, body: 'Your account XX1122 debited by Rs.499 for Netflix subscription.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 499, merchantSubstring: 'Netflix' }, category: 'debit' },
    { id: 14, body: 'Rs.15,000.00 transferred from A/c XX3344 to Landlord via NEFT.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 15000, merchantSubstring: 'Landlord' }, category: 'debit' },
    { id: 15, body: 'INR 250 spent at Starbucks from card ending 5566 on 03/03/2026.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 250, merchantSubstring: 'Starbucks' }, category: 'debit' },
    { id: 16, body: 'Rs.3,200 debited from A/c XX7788 for Electricity Bill payment.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 3200 }, category: 'debit' },
    { id: 17, body: 'Rs 12,500 paid to DMart supermarket from A/c XX9900', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 12500, merchantSubstring: 'DMart' }, category: 'debit' },
    { id: 18, body: 'Your A/c XX1357 is debited by Rs.680.00 at Dominos Pizza on 02-03-2026', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 680 }, category: 'debit' },
    { id: 19, body: 'Rs.4,500 deducted from card XX2468 for Airtel broadband bill.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 4500, merchantSubstring: 'Airtel' }, category: 'debit' },
    { id: 20, body: 'Payment of Rs.899 to Spotify from A/c XX1357.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 899, merchantSubstring: 'Spotify' }, category: 'debit' },
    { id: 21, body: 'Rs.2,750 debited for Rapido ride. A/c XX8642.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 2750 }, category: 'debit' },
    { id: 22, body: 'Your card **4567 has been used for Rs.7,499 at Croma Electronics on 01-Mar-2026.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 7499, merchantSubstring: 'Croma' }, category: 'debit' },
    { id: 23, body: 'Rs.550 debited from A/c XX9753 at KFC on 28/02/2026', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 550 }, category: 'debit' },
    { id: 24, body: 'Rs 1,999 spent at Ajio from A/c XX8520 on 03-03-2026', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 1999, merchantSubstring: 'Ajio' }, category: 'debit' },
    { id: 25, body: 'INR 350.50 debited from your account XX1470 for Blinkit order.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 350.50 }, category: 'debit' },
    { id: 26, body: 'Rs.8,000 withdrawn from ATM via card ending 2580. Ref: ATM123456', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 8000 }, category: 'debit' },
    { id: 27, body: 'Txn of Rs.1,100 at Subway. Card XX3690 on 02-Mar-2026.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 1100, merchantSubstring: 'Subway' }, category: 'debit' },
    { id: 28, body: 'Rs.6,200 paid to Udemy Education from A/c XX4680', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 6200, merchantSubstring: 'Udemy' }, category: 'debit' },
    { id: 29, body: 'Your A/c XX5790 debited Rs.420 at Burger King on 01/03/26.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 420 }, category: 'debit' },
    { id: 30, body: 'Rs 2,100 deducted from A/c XX6800 for FASTag toll payment.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 2100 }, category: 'debit' },
    { id: 31, body: 'Rs.175.00 spent at Zepto. A/c XX7910 debited on 03-Mar-2026.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 175 }, category: 'debit' },
    { id: 32, body: 'Rs.45,000 paid to House Rent via NEFT from A/c XX8020. Ref: NEFT456789', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 45000, merchantSubstring: 'House Rent' }, category: 'debit' },
    { id: 33, body: 'INR 12,999 debited for MakeMyTrip flight booking. A/c XX9130', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 12999, merchantSubstring: 'MakeMyTrip' }, category: 'debit' },
    { id: 34, body: 'Rs.650 debited from A/c XX0240 at McDonald\'s on 02/03/2026', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 650 }, category: 'debit' },
    { id: 35, body: 'Payment of Rs.2,800 to Cult.fit Gym from card XX1350', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 2800 }, category: 'debit' },
    { id: 36, body: 'Rs.999 debited for Hotstar Premium subscription. A/c XX2460', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 999 }, category: 'debit' },
    { id: 37, body: 'Rs 5,500 spent at Reliance Digital from A/c XX3570 on 01-03-2026', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 5500 }, category: 'debit' },
    { id: 38, body: 'Your card XX4680 debited Rs.350 for Dunkin Donuts on 28-Feb-2026', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 350 }, category: 'debit' },
    { id: 39, body: 'Rs.1,450 deducted from A/c XX5790 for Indian Oil Petrol.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 1450 }, category: 'debit' },
    { id: 40, body: 'Rs.22,000 transfer from A/c XX6800 to Insurance Premium via NEFT.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 22000 }, category: 'debit' },
    { id: 41, body: 'Txn of Rs.275 at BookMyShow for movie tickets. Card XX7910', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 275 }, category: 'debit' },
    { id: 42, body: 'Rs.85,000 debited from A/c XX8020 for College Tuition Fee.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 85000 }, category: 'debit' },
    { id: 43, body: 'Rs 950 paid to PhonePe merchant via UPI. A/c XX9130 debited.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 950 }, category: 'debit' },
    { id: 44, body: 'Your A/c XX0240 debited by INR 4,200 at Nykaa on 03-Mar-2026', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 4200 }, category: 'debit' },
    { id: 45, body: 'Rs.1,800 debited from card XX1350 for Goibibo hotel booking.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 1800 }, category: 'debit' },
    { id: 46, body: 'Rs.600 spent at Meesho. A/c XX2460 on 02/03/2026.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 600 }, category: 'debit' },
    { id: 47, body: 'Payment Rs.3,500 to Water Bill from A/c XX3570', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 3500 }, category: 'debit' },
    { id: 48, body: 'Rs.125 debited from A/c XX4680 for Dunzo delivery.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 125 }, category: 'debit' },
    { id: 49, body: 'Rs 750 deducted from card XX5790 at INOX cinemas on 01-Mar-2026.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 750 }, category: 'debit' },
    { id: 50, body: 'INR 11,500 debited from A/c XX6800 for LIC Premium payment.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 11500 }, category: 'debit' },
    { id: 51, body: 'Rs.1,299 paid to Coursera from A/c XX7910. Ref UPI/CR123', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 1299 }, category: 'debit' },
    { id: 52, body: 'Your card XX8020 has been debited Rs.450 at Cafe Coffee Day.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 450 }, category: 'debit' },
    { id: 53, body: 'Rs.2,000 withdrawn from A/c XX9130 via ATM on 28-Feb-2026', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 2000 }, category: 'debit' },
    { id: 54, body: 'Rs.380 debited for Snapdeal purchase. A/c XX0240 on 03/03/2026.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 380 }, category: 'debit' },
    { id: 55, body: 'Rs.950 dr from A/c XX1350 to Cleartrip on 02-Mar-2026', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 950 }, category: 'debit' },
    { id: 56, body: 'Rs 5,000 debited from A/c XX2460 for Vodafone postpaid bill.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 5000 }, category: 'debit' },
    { id: 57, body: 'Txn of Rs.1,650 at Big Bazaar on 01/03/2026. Card XX3570.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 1650 }, category: 'debit' },
    { id: 58, body: 'Rs.8,500 paid to School Fee from A/c XX4680 via NEFT.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 8500 }, category: 'debit' },
    { id: 59, body: 'Your A/c XX5790 debited by Rs.225 at Gaana Music on 28-Feb-2026.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 225 }, category: 'debit' },
    { id: 60, body: 'Rs.18,000 debited from card XX6800 for Star Health Insurance.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 18000 }, category: 'debit' },
    { id: 61, body: 'Rs 3,999 spent at JioMart from A/c XX7910 on 03-03-2026', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 3999 }, category: 'debit' },
    { id: 62, body: 'Rs.1,500 debited from A/c XX8020 to HP Fuel Station.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 1500 }, category: 'debit' },
    { id: 63, body: 'Payment of Rs.7,200 to Byju\'s Education from card XX9130', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 7200 }, category: 'debit' },
    { id: 64, body: 'Rs.990 paid to YouTube Premium. A/c XX0240 debited.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 990 }, category: 'debit' },
    { id: 65, body: 'Rs 2,500 debited from A/c XX1350 for Metro Card Recharge.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 2500 }, category: 'debit' },
    { id: 66, body: 'Your card XX2460 used for Rs.4,800 at IRCTC Railways on 02-Mar-2026', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 4800 }, category: 'debit' },
    { id: 67, body: 'Rs.320 debited at Biryani By Kilo from A/c XX3570.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 320 }, category: 'debit' },
    { id: 68, body: 'INR 6,500 deducted from A/c XX4680 for Parking Fee.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 6500 }, category: 'debit' },
    { id: 69, body: 'Rs.1,200 spent via UPI at Unacademy. A/c XX5790 on 01/03/2026.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 1200 }, category: 'debit' },
    { id: 70, body: 'Rs 450 debited from A/c XX6800 for Swiggy Instamart.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 450 }, category: 'debit' },
    { id: 71, body: 'Rs.16,000 paid to Max Bupa Health Insurance. A/c XX7910', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 16000 }, category: 'debit' },
    { id: 72, body: 'Txn of Rs.850 at Pizza Hut on 28-Feb-2026. Card XX8020.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 850 }, category: 'debit' },
    { id: 73, body: 'Rs.3,000 debited from A/c XX9130 for Gas Bill payment.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 3000 }, category: 'debit' },
    { id: 74, body: 'Rs 20,000 transfer from A/c XX0240 to Yatra travel booking.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 20000 }, category: 'debit' },
    { id: 75, body: 'Your A/c XX1350 debited Rs.575 for Grofers grocery order.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 575 }, category: 'debit' },
    { id: 76, body: 'Rs.9,999 paid to RedBus. Card XX2460 on 03-Mar-2026.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 9999 }, category: 'debit' },
    { id: 77, body: 'Rs.1,100 debited from A/c XX3570 to EatFit Meals.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 1100 }, category: 'debit' },
    { id: 78, body: 'INR 425 spent at Shopsy from card XX4680 on 02/03/2026.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 425 }, category: 'debit' },
    { id: 79, body: 'Rs.7,500 deducted from A/c XX5790 for Jio Fiber broadband.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 7500 }, category: 'debit' },
    { id: 80, body: 'Rs 35,000 debited from A/c XX6800 for BSNL annual plan.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 35000 }, category: 'debit' },
    { id: 81, body: 'Rs.290 paid to FoodPanda via UPI. A/c XX7910.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 290 }, category: 'debit' },
    { id: 82, body: 'Rs.4,000 debited for Bharat Petroleum fuel. Card XX8020 on 01-Mar-2026.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 4000 }, category: 'debit' },
    { id: 83, body: 'Payment of Rs.13,500 to Vacation booking from A/c XX9130', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 13500 }, category: 'debit' },
    { id: 84, body: 'Your card XX0240 charged Rs.2,350 at Mall of India on 28-Feb-2026', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 2350 }, category: 'debit' },
    { id: 85, body: 'Rs 175 debited from A/c XX1350 at Kirana Store.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 175 }, category: 'debit' },
    { id: 86, body: 'Rs.50,000 debited from A/c XX2460 for SBI Auto Renewal membership.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 50000 }, category: 'debit' },
    { id: 87, body: 'Rs.660 spent at Cafe restaurant from A/c XX3570 on 03-03-2026', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 660 }, category: 'debit' },
    { id: 88, body: 'INR 1,750 debited for Wifi bill payment. A/c XX4680.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 1750 }, category: 'debit' },
    { id: 89, body: 'Rs.400 deducted from card XX5790 at Dhaba restaurant.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 400 }, category: 'debit' },
    { id: 90, body: 'Rs 95,000 paid to University Fee from A/c XX6800 via NEFT.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 95000 }, category: 'debit' },
    { id: 91, body: 'Rs.520 debited from A/c XX7910 at Electric Bill payment.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 520 }, category: 'debit' },
    { id: 92, body: 'Your A/c XX8020 debited by Rs.3,800 for Fitness membership.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 3800 }, category: 'debit' },
    { id: 93, body: 'Txn of Rs.999 at Amazon Prime Video. Card XX9130.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 999 }, category: 'debit' },
    { id: 94, body: 'Rs.14,200 debited from A/c XX0240 for Power Bill.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 14200 }, category: 'debit' },
    { id: 95, body: 'Rs 280 spent at Grocery store. A/c XX1350 on 02-Mar-2026.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 280 }, category: 'debit' },
    { id: 96, body: 'Rs.6,999 paid to Supermarket from card XX2460.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 6999 }, category: 'debit' },
    { id: 97, body: 'Rs.155 debited from A/c XX3570 for Vi recharge.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 155 }, category: 'debit' },
    { id: 98, body: 'INR 8,900 deducted from card XX4680 at Toll Plaza FASTag.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 8900 }, category: 'debit' },
    { id: 99, body: 'Rs.2,200 debited from A/c XX5790 for Fuel Station.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 2200 }, category: 'debit' },
    { id: 100, body: 'Rs 340 paid to Swiggy food delivery. A/c XX6800.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 340 }, category: 'debit' },
    { id: 101, body: 'Rs.75,000 debited from A/c XX7910 for Landlord House Rent.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 75000, merchantSubstring: 'Landlord' }, category: 'debit' },
    { id: 102, body: 'Your card XX8020 used Rs.1,375 at Zomato on 01-Mar-2026', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 1375 }, category: 'debit' },
    { id: 103, body: 'Rs.480 debited from A/c XX9130 at Subway Restaurant.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 480 }, category: 'debit' },
    { id: 104, body: 'Rs 5,600 spent at Flipkart from card XX0240 on 28/02/2026.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 5600 }, category: 'debit' },
    { id: 105, body: 'Rs.1,050 deducted from A/c XX1350 for Amazon purchase.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 1050 }, category: 'debit' },
    { id: 106, body: 'Payment Rs.3,100 from card XX2460 to Myntra Shopping.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 3100 }, category: 'debit' },
    { id: 107, body: 'Rs.11,000 debited from A/c XX3570 for Life Insurance Premium.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 11000 }, category: 'debit' },
    { id: 108, body: 'Txn of Rs.725 at Uber Eats. A/c XX4680 on 03-Mar-2026.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 725 }, category: 'debit' },
    { id: 109, body: 'Rs.2,450 paid to Amazon.in via UPI. Card XX5790 debited.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 2450 }, category: 'debit' },
    { id: 110, body: 'Rs 19,500 debited from A/c XX6800 for Health Insurance.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 19500 }, category: 'debit' },
    { id: 111, body: 'Your A/c XX7910 debited Rs.890 for Paytm merchant payment.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 890 }, category: 'debit' },
    { id: 112, body: 'Rs.4,350 deducted from card XX8020 for Ola ride on 02-Mar-2026.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 4350 }, category: 'debit' },
    { id: 113, body: 'Rs.1,600 debited from A/c XX9130 at Gym Membership renewal.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'expense', amount: 1600 }, category: 'debit' },
    { id: 114, body: 'INR 550 spent at KFC from A/c XX0240 on 01/03/2026.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 550 }, category: 'debit' },
    { id: 115, body: 'Rs.25,000 paid to Course Fee from A/c XX1350 via IMPS.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 25000 }, category: 'debit' },
    { id: 116, body: 'Rs 760 debited from card XX2460 at Starbucks Coffee.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 760 }, category: 'debit' },
    { id: 117, body: 'Rs.42,000 debited from A/c XX3570 for Vacation Package.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'expense', amount: 42000 }, category: 'debit' },
    { id: 118, body: 'Rs.195 deducted from A/c XX4680 at Swiggy on 28-Feb-2026.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'expense', amount: 195 }, category: 'debit' },
    { id: 119, body: 'Payment of Rs.7,800 to Amazon Shopping from card XX5790', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'expense', amount: 7800 }, category: 'debit' },
    { id: 120, body: 'Rs.3,250 debited from A/c XX6800 for Electric Power bill.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'expense', amount: 3250 }, category: 'debit' },

    // ═════════════════════════════════════════════
    // CREDIT SAMPLES (121–160)
    // ═════════════════════════════════════════════
    { id: 121, body: 'Rs.50,000 credited to A/c XX1234 by NEFT. Salary for Feb 2026.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 50000 }, category: 'credit' },
    { id: 122, body: 'Your A/c XX5678 is credited by Rs.25,000 via IMPS on 01-Mar-2026.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'income', amount: 25000 }, category: 'credit' },
    { id: 123, body: 'Rs 12,500 received in A/c XX4321 from PayTM refund.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 12500 }, category: 'credit' },
    { id: 124, body: 'INR 75,000.00 has been credited to your account XX9876. Salary credit.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'income', amount: 75000 }, category: 'credit' },
    { id: 125, body: 'Rs.3,500 credited to A/c XX4567 for Amazon refund on 03-Mar-2026.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'income', amount: 3500 }, category: 'credit' },
    { id: 126, body: 'Refund of Rs.1,299 credited to card XX1111 from Flipkart.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 1299 }, category: 'credit' },
    { id: 127, body: 'Rs.8,000 received in A/c XX2222 via UPI from Freelance Client.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'income', amount: 8000 }, category: 'credit' },
    { id: 128, body: 'Rs 1,50,000 credited to A/c XX3456 by NEFT. Monthly Salary.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 150000 }, category: 'credit' },
    { id: 129, body: 'Your A/c XX6789 credited with Rs.4,200 refund from Myntra.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'income', amount: 4200 }, category: 'credit' },
    { id: 130, body: 'Rs.15,000 credited to A/c XX4444. IMPS CR from Investment Returns.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 15000 }, category: 'credit' },
    { id: 131, body: 'INR 2,000 received in A/c XX5555 from GPay. Ref: UPI/PAY789', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'income', amount: 2000 }, category: 'credit' },
    { id: 132, body: 'Rs.65,000 credited to your A/c XX7890 by SAL CREDIT for March 2026.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 65000 }, category: 'credit' },
    { id: 133, body: 'Refund of Rs.899 to card XX1122 from Swiggy order cancellation.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'income', amount: 899 }, category: 'credit' },
    { id: 134, body: 'Rs 5,500 credited to A/c XX3344 via NEFT from Client Payment.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'income', amount: 5500 }, category: 'credit' },
    { id: 135, body: 'Rs.10,000.00 deposited to A/c XX5566 on 02-Mar-2026. Cash deposit.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 10000 }, category: 'credit' },
    { id: 136, body: 'Rs.2,750 credited to A/c XX7788 for Zomato refund.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'income', amount: 2750 }, category: 'credit' },
    { id: 137, body: 'INR 45,000 received in A/c XX9900. Freelance project payment.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 45000 }, category: 'credit' },
    { id: 138, body: 'Rs.1,500 refund of Rs.1,500 to A/c XX1357 from BookMyShow.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'income', amount: 1500 }, category: 'credit' },
    { id: 139, body: 'Rs 30,000 credited to A/c XX2468 via RTGS. Dividend payout.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 30000 }, category: 'credit' },
    { id: 140, body: 'Your A/c XX1357 is credited with Rs.7,500 from Razorpay.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'income', amount: 7500 }, category: 'credit' },
    { id: 141, body: 'Rs.80,000 credited to A/c XX5790 by NEFT. Salary for Mar 2026.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 80000 }, category: 'credit' },
    { id: 142, body: 'Rs 950 cashback of Rs.950 credited to card XX8642.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'income', amount: 950 }, category: 'credit' },
    { id: 143, body: 'Rs.22,500 deposited to A/c XX9753. IMPS from Business Income.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'income', amount: 22500 }, category: 'credit' },
    { id: 144, body: 'Refund of Rs.3,200 credited to your A/c XX8520 from Uber.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 3200 }, category: 'credit' },
    { id: 145, body: 'INR 1,00,000 credited to A/c XX1470 by NEFT. Annual Bonus.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'income', amount: 100000 }, category: 'credit' },
    { id: 146, body: 'Rs.6,000 received in A/c XX2580 from GPay transfer.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 6000 }, category: 'credit' },
    { id: 147, body: 'Rs 18,000 credit to A/c XX3690 via UPI. Freelance work.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'income', amount: 18000 }, category: 'credit' },
    { id: 148, body: 'Rs.4,500 credited to card XX4680 as refund from Amazon.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 4500 }, category: 'credit' },
    { id: 149, body: 'Your A/c XX5790 credited Rs.35,000 by NEFT. Consulting fee.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'income', amount: 35000 }, category: 'credit' },
    { id: 150, body: 'Rs.550 refund of Rs.550 to A/c XX6800 from Blinkit.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 550 }, category: 'credit' },
    { id: 151, body: 'INR 90,000 credited to A/c XX7910. Salary March 2026.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'income', amount: 90000 }, category: 'credit' },
    { id: 152, body: 'Rs 2,200 received in A/c XX8020 from PhonePe.', sender: 'DM-KOTAKB', expected: { isTransaction: true, type: 'income', amount: 2200 }, category: 'credit' },
    { id: 153, body: 'Rs.12,000 deposited to A/c XX9130 on 01-Mar-2026. NEFT deposit.', sender: 'JD-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 12000 }, category: 'credit' },
    { id: 154, body: 'Rs.1,800 credited to A/c XX0240 for Ola refund.', sender: 'BW-SBIINB', expected: { isTransaction: true, type: 'income', amount: 1800 }, category: 'credit' },
    { id: 155, body: 'Rs 40,000 credited to A/c XX1350 via RTGS. Project milestone.', sender: 'QD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 40000 }, category: 'credit' },
    { id: 156, body: 'Refund of Rs.2,999 to card XX2460 from Netflix.', sender: 'AX-AXISBK', expected: { isTransaction: true, type: 'income', amount: 2999 }, category: 'credit' },
    { id: 157, body: 'Rs.55,000 credited to your A/c XX3570. NEFT Salary deposit.', sender: 'VM-HDFCBK', expected: { isTransaction: true, type: 'income', amount: 55000 }, category: 'credit' },
    { id: 158, body: 'INR 3,750 received in A/c XX4680 from Razorpay settlement.', sender: 'AD-SBIINB', expected: { isTransaction: true, type: 'income', amount: 3750 }, category: 'credit' },
    { id: 159, body: 'Rs.700 refund of Rs.700 credited to A/c XX5790 from Ajio.', sender: 'VD-ICICIB', expected: { isTransaction: true, type: 'income', amount: 700 }, category: 'credit' },
    { id: 160, body: 'Rs 1,20,000 credited to A/c XX6800 by NEFT. Quarterly bonus.', sender: 'BZ-AXISBK', expected: { isTransaction: true, type: 'income', amount: 120000 }, category: 'credit' },

    // ═════════════════════════════════════════════
    // OTP SAMPLES (161–180) — must be IGNORED
    // ═════════════════════════════════════════════
    { id: 161, body: 'Your OTP for transaction is 582931. Valid for 5 minutes. Do not share.', sender: 'VM-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 162, body: '123456 is your One Time Password for login. Expires in 10 min.', sender: 'AD-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 163, body: 'Your verification code is 789012. Use it to verify your identity.', sender: 'VD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 164, body: 'OTP 345678 for Rs.5000 transaction at Amazon. If not done by you, call 18001234.', sender: 'BZ-AXISBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 165, body: 'Your HDFC Bank OTP is 901234. DO NOT share this with anyone.', sender: 'VM-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 166, body: 'PIN for your card ending 5678 will expire soon. Visit branch to renew.', sender: 'AD-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 167, body: '654321 is your one time password for ICICI Net Banking login.', sender: 'VD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 168, body: 'Your verification code for GPay is 112233. Valid for 3 min.', sender: 'BZ-GPAY', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 169, body: 'OTP: 998877 for adding beneficiary A/c XX4321. Do not share.', sender: 'DM-KOTAKB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 170, body: 'Your PhonePe OTP is 556677. Transaction Rs.2000 to Amazon.', sender: 'JD-PHONEPE', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 171, body: 'Transaction failed. Rs.500 payment to Swiggy could not be processed.', sender: 'VM-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 172, body: 'Your transaction of Rs.1200 was declined due to insufficient funds.', sender: 'AD-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 173, body: 'Transaction unsuccessful. Rs.3000 payment at Flipkart not processed.', sender: 'VD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 174, body: 'Your available balance in A/c XX1234 is Rs.45,678.90 as on 03-Mar-2026.', sender: 'BZ-AXISBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 175, body: 'Avl Bal in A/c XX5678: Rs.12,345.67. Min bal reqd: Rs.10,000.', sender: 'DM-KOTAKB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 176, body: 'Account balance is Rs.89,000 in XX4567 as of 02-Mar-2026.', sender: 'JD-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 177, body: 'OTP for your net banking session is 223344. Expires in 5 mins.', sender: 'BW-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 178, body: 'Reversal initiated for Rs.2500 transaction. Refund in 5-7 days.', sender: 'QD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 179, body: 'Your one time password for fund transfer is 887766. Do not share with anyone.', sender: 'AX-AXISBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },
    { id: 180, body: 'Failed transaction of Rs.750 at Zomato. Please retry. Ref: TXN999888.', sender: 'VM-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'otp' },

    // ═════════════════════════════════════════════
    // PROMO SAMPLES (181–200) — must be IGNORED
    // ═════════════════════════════════════════════
    { id: 181, body: 'Congratulations! You are pre-approved for a personal loan of Rs.5,00,000. Apply now!', sender: 'VM-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 182, body: 'Exclusive offer! Get flat 10% cashback on your next Amazon purchase. T&C apply.', sender: 'AD-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 183, body: 'Upgrade your plan to Premium and get 2X rewards! Click here: https://bank.co/offer', sender: 'VD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 184, body: 'Dear Customer, enjoy special offers on credit card spends this weekend! T&C apply.', sender: 'BZ-AXISBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 185, body: 'EMI available on your Rs.25,000 purchase! Convert now at 0% interest. Call 1800123.', sender: 'DM-KOTAKB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 186, body: 'Loan offer: Pre-approved loan of Rs.10,00,000 at 10.5% p.a. Apply link: https://bnk.co/ln', sender: 'JD-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 187, body: 'Get cashback of Rs.200 on your next Rs.1000 UPI payment! Offer valid till 31-Mar-2026.', sender: 'BW-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 188, body: 'Your credit card is eligible for free airport lounge access. Activate now!', sender: 'QD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 189, body: 'Promo: Earn 5X reward points on dining spends this month! Shop now.', sender: 'AX-AXISBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 190, body: 'Dear Customer, special deals on home loan! Interest starting 8.5% p.a. Call us.', sender: 'VM-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 191, body: 'Get flat 15% off on Swiggy with SBI card! Use code: SBI15. T&C apply. Link: sbi.co/food', sender: 'AD-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 192, body: 'Your FD of Rs.1,00,000 has matured. Renew now at attractive rates. Click here to renew.', sender: 'VD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 193, body: 'Win an iPhone 15! Spend Rs.5000 on your Axis card this week. T&C: https://axis.co/win', sender: 'BZ-AXISBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 194, body: 'Promotion: Zero joining fee on Kotak credit card! Apply now: https://kotak.co/cc', sender: 'DM-KOTAKB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 195, body: 'Exclusive for you: Gold loan at lowest interest rate. Pre-approved Rs.3,00,000. Apply!', sender: 'JD-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 196, body: 'Dear Customer, your reward points (2450) are expiring soon! Redeem now.', sender: 'BW-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 197, body: 'Special offer: Get cashback up to Rs.500 on bill payments. Offer ends 15-Mar-2026. Link: icici.co/bills', sender: 'QD-ICICIB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 198, body: 'You have been pre-approved for Axis credit card with Rs.5L limit! Click here to apply.', sender: 'AX-AXISBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 199, body: 'Flash Sale! Flat 20% off on all HDFC card transactions at Amazon. Today only!', sender: 'VM-HDFCBK', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
    { id: 200, body: 'Dear Customer, your SBI card offer: 0% EMI on purchases above Rs.3000. T&C apply.', sender: 'AD-SBIINB', expected: { isTransaction: false, type: null, amount: null }, category: 'promo' },
];
